### ISSUE TITLE
Deploying to shinyapps.io fails with "certificate verification failed"

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/rsconnect#220]
Using `rsconnect 0.8.7` deploying to shinyapps.io fails with this error:

```
Error in function (type, msg, asError = TRUE)  : 
  SSL: certificate verification failed (result: 5)
Calls: <Anonymous> ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
```

I can deploy to Connect servers with no issue.

**Comment by fereshtehRS** [comment]
Should mention that going back to `0.8.5` fixes the problem.

**Comment by JsizzleR** [comment]
I'm unable to link account with Shinyapps.io on 0.8.7, receive this error:

![image](https://user-images.githubusercontent.com/27960665/32965974-56bfb204-cba6-11e7-9b0e-8077488d7322.png)

Reviewing permissions:

![image](https://user-images.githubusercontent.com/27960665/32966026-85440d5a-cba6-11e7-84e1-5acaaff4a798.png)

**Comment by jmcphers** [comment]
@JsizzleR I couldn't replicate that on Linux or Mac, but I think I can guess what's going on -- your existing cert store probably has low permissions and they're coming along for the ride when we try to create our own cert store. Could you tell me if this fixes it?

    > devtools::install_github("rstudio/rsconnect", ref = "bugfix/cert-store-permissions")

**Comment by jmcphers** [comment]
@fereshtehRS I can't replicate that. :-/ What platform were you on? What HTTP transport option(s) were you using?

**Comment by JsizzleR** [comment]
thanks @jmcphers , that solved the permission error when trying to link the account.  I was then able to deploy to shinyapps.io

**Comment by jmcphers** [comment]
@JsizzleR Appreciate the quick followup, I've just pushed it to master in case anyone else is affected.

**Comment by fereshtehRS** [comment]
@jmcphers I see the error on MacOS 10.11.5

On the same Mac, when I publish using a command it works fine; only from Publish menu I get the error.

I tried it on Ubuntu, and that works fine from menu.

**Comment by jmcphers** [comment]
Interesting! What HTTP transport are you using for publishing? Can you post the diagnostic log?

**Comment by fereshtehRS** [comment]
Not sure what the HTTP transport would be in this context. If you mean `http` vs `https`, my server listing shows this for shinyapps.io:

`http://shinyapps.io/__api__`

Here is the diagnostics log:

[diagnostics-report.txt](https://github.com/rstudio/rsconnect/files/1484333/diagnostics-report.txt)

**Comment by fereshtehRS** [comment]
@jmcphers I have tested with the latest development, and was still seeing the issue. Also tested with  the branch `bugfix/cert-store-permissions` version.
In #223 it is mentioned that the fix is for Windows. I am running on Mac.

**Comment by jvschoen** [comment]
I've tried running the bugfix, but still get the same error. I also and using a Mac. Has there been any update on this?

This is the error:
Error in function (type, msg, asError = TRUE)  : 
  SSL: certificate verification failed (result: 5)
