### ISSUE TITLE
Unable to set account info

### ISSUE THREAD

**Issue by nm250** [rstudio/rsconnect#329]
Hi everyone,
I recently updated my rsconnect package and now I can't use it anymore. This is the error message I get when I try to set my account:

`rsconnect::setAccountInfo(name='lonza-qsar', token='XXXXXXXXXXXXXXXXXXX', secret='XXXXXXXXXXXXXXXXXXX'`

`Error in if (isContentType(response, "application/json")) { : 
  argument is of length zero
In addition: Warning message:
In readLines(con = conn) :
  incomplete final line found on 'C:\Users\nmccann\AppData\Local\Temp\RtmpyuryyL\file285428817d71'`

I thought this looked similar to issue #318, but the install from devtools, suggested by jmcphers didn't help - I still get the same error message. 
The file mentionned in the error message above contains:

> HTTP/1.1 200 Connection Established
Proxy-Agent: Zscaler/5.6

> HTTP/1.1 200 OK
Date: Fri, 04 Jan 2019 09:00:31 GMT
Content-Type: application/json; charset=UTF-8
Content-Length: 482
Connection: keep-alive
Server: nginx/1.10.3 (Ubuntu)
Etag: "907ba921d7ba5e0af6fd8dc8b259e27ada88501e"
Access-Control-Allow-Origin: https://rstudio.cloud

> {"github_auth_token": null, "first_name": null, "last_name": null, "display_name": null, "grant": null, "email_verified": true, "picture_url": "https://www.gravatar.com/avatar/d242c56564be5d86f85af4310b53297b", "github_auth_id": null, "email": "XXX@XXX.com", "updated_time": "2017-08-11T12:19:55", "local_auth": true, "location": null, "created_time": "2017-05-15T08:19:07", "organization": null, "referral": null, "homepage": null, "id": 99792, "google_auth_id": null}

Thanks for your help

My session info:
> devtools::session_info()
 Session info ------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.2 (2018-12-20)
 os       Windows 7 x64 SP 1          
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  German_Switzerland.1252     
 ctype    German_Switzerland.1252     
 tz       Europe/Berlin               
 date     2019-01-04                  
 Packages ----------------------------------------------------------------------------------------
 package     * version     date       lib source                            
 assertthat    0.2.0       2017-04-11 [1] CRAN (R 3.5.1)                    
 backports     1.1.3       2018-12-14 [1] CRAN (R 3.5.2)                    
 callr         3.1.1       2018-12-21 [1] CRAN (R 3.5.2)                    
 cli           1.0.1       2018-09-25 [1] CRAN (R 3.5.2)                    
 crayon        1.3.4       2017-09-16 [1] CRAN (R 3.5.1)                    
 curl          3.2         2018-03-28 [1] CRAN (R 3.5.1)                    
 desc          1.2.0       2018-05-01 [1] CRAN (R 3.5.2)                    
 devtools    * 2.0.1       2018-10-26 [1] CRAN (R 3.5.2)                    
 digest        0.6.18      2018-10-10 [1] CRAN (R 3.5.2)                    
 fs            1.2.6       2018-08-23 [1] CRAN (R 3.5.1)                    
 glue          1.3.0       2018-07-17 [1] CRAN (R 3.5.1)                    
 magrittr      1.5         2014-11-22 [1] CRAN (R 3.5.1)                    
 memoise       1.1.0       2017-04-21 [1] CRAN (R 3.5.1)                    
 openssl       1.1         2018-11-15 [1] CRAN (R 3.5.2)                    
 pkgbuild      1.0.2       2018-10-16 [1] CRAN (R 3.5.2)                    
 pkgload       1.0.2       2018-10-29 [1] CRAN (R 3.5.2)                    
 prettyunits   1.0.2       2015-07-13 [1] CRAN (R 3.5.1)                    
 processx      3.2.1       2018-12-05 [1] CRAN (R 3.5.2)                    
 ps            1.3.0       2018-12-21 [1] CRAN (R 3.5.2)                    
 R6            2.3.0       2018-10-04 [1] CRAN (R 3.5.2)                    
 Rcpp          1.0.0       2018-11-07 [1] CRAN (R 3.5.1)                    
 remotes       2.0.2       2018-10-30 [1] CRAN (R 3.5.2)                    
 rlang         0.3.0.1     2018-10-25 [1] CRAN (R 3.5.1)                    
 rprojroot     1.3-2       2018-01-03 [1] CRAN (R 3.5.1)                    
 rsconnect   * 0.8.11-9000 2019-01-04 [1] Github (rstudio/rsconnect@47b7171)
 rstudioapi    0.8         2018-10-02 [1] CRAN (R 3.5.2)                    
 sessioninfo   1.1.1       2018-11-05 [1] CRAN (R 3.5.2)                    
 testthat      2.0.1       2018-10-13 [1] CRAN (R 3.5.1)                    
 usethis     * 1.4.0       2018-08-14 [1] CRAN (R 3.5.2)                    
 withr         2.1.2       2018-03-15 [1] CRAN (R 3.5.1)                    
 yaml          2.2.0       2018-07-25 [1] CRAN (R 3.5.2)

**Comment by jmcphers** [comment]
How did you updated rsconnect, exactly (what command did you run)? This issue should be fixed in 0.8.12-9000 (you're using 0.8.11-9000).

**Comment by nm250** [comment]
Hi,
I ran install.packages(rsconnect). I just tried it again – re-installing, and checked that the package version is 0.8.12, but when I try to setAccountInfo, I get the same error message.
Cheers,
Nichola

**Comment by jmcphers** [comment]
> checked that the package version is 0.8.12

The version you need is 0.8.12-9000, which is newer than you will get from CRAN. You need to install from Github to fix this issue.

    > devtools::install_github("rstudio/rsconnect")

(we'll be submitting to CRAN fairly soon!)

**Comment by nm250** [comment]
Hi Jonathon,
Thanks for the advice. I installed from Github, but I still get the same error message (see below)
[cid:image001.png@01D4A667.1E2E4C60]

**Comment by amracel** [comment]
Hi Johnathan -

I ran into the same issue. I'm using version 0.8.13. Note: this didn't happen last night on my Linux box. But it is happening this morning on a Windows box. I am also behind a firewall here. Is that part of the issue?

full message:

```
Error in if (isContentType(response, "application/json")) { : 
  argument is of length zero
In addition: Warning message:
In readLines(con = conn) :
  incomplete final line found on '<temp file>'
```

**Comment by jmcphers** [comment]
Should be fixed in 0.8.15 with https://github.com/rstudio/rsconnect/pull/311 (let me know if you're still seeing it!)
